version: '3.8'

services:
  job:
    build:
      context: .
      dockerfile: Dockerfile
    image: pg-cron-ts
    container_name: worker
    volumes:
      - ./jobs:/app/jobs
    restart: unless-stopped
